name: caurishop

services:

  app:
    image: ghcr.io/${GITHUB_REPOSITORY:-fouzo09/caurishop}:${IMAGE_TAG:-latest}
    container_name: caurishop_app
    restart: unless-stopped
    env_file: .env
    volumes:
      - storage_data:/var/www/html/storage/app/public
    ports:
      - "80:80"
      - "443:443"
    networks:
      - caurishop

volumes:
  storage_data:

networks:
  caurishop:
    driver: bridge
